### ISSUE TITLE
Encoding json array

### ISSUE THREAD

**Issue by dodalovic** [vandium-io/jwtgen#6]
Hi, I tried, but unsuccessfully, to encode something like:

```bash
jwtgen -a HS256 -s "secret" -c "jti=58ee09a8e64ada000735c672" -c "roles=[\"ROLE_ADMIN\"]" -e 3600
```
without success. Are array values supported?

Thanks

**Comment by dc00p** [comment]
No, currently both arrays and objects are stringified for each claim.

**Comment by dodalovic** [comment]
@dc00p Is it at least on roadmap? I like tool but due to this constraint we can't use it in our team.

**Comment by dc00p** [comment]
Yes.

**Comment by dc00p** [comment]
Take a look the 2.x branch

**Comment by dc00p** [comment]
Take a look at the 2.x branch

**Comment by dodalovic** [comment]
@dc00p Nice. Is it to be pulled to master any time soon?
